export const SITE_PAGES = [
  { name: "home", label: "Home", path: "/index.html" },
  { name: "about", label: "About Us", path: "/about.html" },
  { name: "membership", label: "Membership", path: "/membership.html" },
  { name: "fixtures", label: "Fixtures", path: "/fixtures.html" },
  { name: "news", label: "News & Events", path: "/news.html" },
  { name: "gallery", label: "Gallery", path: "/gallery.html" },
  { name: "contact", label: "Contact Us", path: "/contact.html" },
  { name: "sponsors", label: "Sponsors", path: "/sponsors.html" },
  { name: "honours", label: "Honours", path: "/honours.html" },
  { name: "archive", label: "Sandy Deans Archive", path: "/archive.html" },
  { name: "history", label: "History", path: "/history.html" },
  { name: "signup", label: "Create Account", path: "/signup.html" },
  { name: "live-scoring", label: "Live Scores", path: "/live-scoring.html" },
  {
    name: "news-presentation-dance-2025",
    label: "News article: Presentation Dance 2025",
    path: "/News%20articles/presentation-dance-2025.html",
  },
  {
    name: "album-presentation-dance-2025",
    label: "Album: Presentation Dance 2025",
    path: "/PhotoAlbums/presentation-dance-2025.html",
  },
  {
    name: "album-charlie-mcneil-memorial-2025",
    label: "Album: Charlie McNeil Memorial 2025",
    path: "/PhotoAlbums/charlie-mcneil-memorial-2025.html",
  },
  {
    name: "album-top-15-final-2025",
    label: "Album: Top 15 Final 2025",
    path: "/PhotoAlbums/top-15-final-2025.html",
  },
  {
    name: "album-twa-peters-memorial-2025",
    label: "Album: Twa Peters Memorial 2025",
    path: "/PhotoAlbums/twa-peters-memorial-2025.html",
  },
];
